### PR TITLE
Add support for dynamic imports

### PR DESCRIPTION
**Pull request by marcuslindblom**
Fixes issue with dynamic imports #43

### CODE REVIEW

**Comment by osdevisnot** [comment]
@marcuslindblom thank you for your contributions and apologies for delayed responses on #43.

For this PR, I am wondering why we `inlineDynamicImports` only for ESM entry? Any specific reason to skip commonjs and umd bundles?

**Comment by marcuslindblom** [comment]
Sorry, I was fixing _my_ problem and forgot about the bigger picture. Do you think it's a good idea to add this to commonjs and umd bundles as well?

**Comment by osdevisnot** [comment]
Can we generate separate chunk as oppposed to inlining them?

**Comment by marcuslindblom** [comment]
Not sure what the benefits are actually. For me I prefer inlining them because the only reason I use Klap is to bundle es modules to gain performance. I'm also a "no framework" dude so I don't know much about code splitting and tree shaking. Maybe we should make this configurable?

**Comment by marcuslindblom** [comment]
@osdevisnot What do you think? ☝️

**Comment by osdevisnot** [comment]
I haven't fully consolidated my thoughts on this yet, but it seems rather unintuitive to me to inline the dynamic imports. Basically there are two use cases. Your code wanting to lazy load a file/portion of code and you using a dependency that wants to lazy load file/portion of it's code.

The answer however is going to depend on the usecase it specific library you are building with klap.

We in klap therefore should not assume one way or the other and expose this as a configuration option.

**Comment by osdevisnot** [comment]
The default value for `inlineDynamicImports` is false, but we should be able to add a new `--inline` flag in `options.js` to let users configure this.

**Comment by osdevisnot** [comment]
@marcuslindblom - Can you point me to code you are attempting to compile with `inline` imports? There are multiple formats with varying degree of support across plugins. Also, rollup does not support multiple output chunks for `cjs` and `umd` targets.

**Comment by marcuslindblom** [comment]
@osdevisnot That sounds like a reasonable thing to do. I also think that the configuration option will fit most users.

This is one example on how I use dynamic imports in my code. I don't have the complete code in a public repository.

```js
export default () => {
  switch (env()) {
    case 'Development':
      return import('/client/index.js');
    default:
      return import('https://unpkg.com/@wieldyapp/wieldy@0.0.1-preview.32/dist/index.esm.js');
  }
};
```

**Comment by osdevisnot** [comment]
@marcuslindblom thank you for your patience on this one. I tried the dynamic imports in various scenarios and it seems the feature might not be that useful after all. One of the goal for `klap` is to be consistent across build targets, and dynamic imports do not offer that for other build targets.

That said, let me prepare a new release with `inlineDynamicImports: true`.

Since this PR does not address CJS and UMD, I will close this and add the feature in separate commit.

**Comment by osdevisnot** [comment]
@all-contributors please add @marcuslindblom for code.

**Pull request closed without merging**
